### ISSUE TITLE
Custom Application

### ISSUE THREAD

**Issue by terry212** [MyThemeShop/WP-Review-by-MyThemeShop#23]
Not really an issue, but more so of a question. Can I use this plugin to rate users that have an author role? I have a page that displays the authors and want users to rate the authors and to leave a small review of the author. Is this possible?

**Comment by balazsp** [comment]
Hi Terry,
It is not possible to rate authors with the plugin, but here is what you could do: create a new Custom Post Type, e.g. "Author Reviews" (by adding code to your theme files or using some _CPT Manager_ plugin), create one review for each author, and insert the shortcode or the template tag wherever you want the rating to appear.
Hope that helps.
